package suggestdraft

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"agent-harness/internal/domain/draftmeta"
)

func Write(root, draftWikiDir, title, targetWiki, targetType, output string) (string, error) {
	body := strings.TrimSpace(StripLLMOutputPreamble(StripMarkdownFence(output)))
	if body == "" {
		return "", fmt.Errorf("LLM output was empty")
	}
	if !strings.HasPrefix(body, "---\n") {
		body = Frontmatter(title, targetWiki, targetType) + "\n" + body + "\n"
	}
	meta := draftmeta.ParseFrontmatter(body)
	draftTitle := meta["title"]
	if draftTitle == "" {
		draftTitle = title
	}
	if draftTitle == "" {
		draftTitle = "draft wiki candidate"
	}
	filename := time.Now().Format(time.DateOnly) + "-" + Slugify(draftTitle) + ".md"
	path := filepath.Join(root, filepath.FromSlash(draftWikiDir), "draft", filename)
	if _, err := os.Stat(path); err == nil {
		return "", fmt.Errorf("draft already exists: %s", path)
	} else if !os.IsNotExist(err) {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(body+"\n"), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func Frontmatter(title, targetWiki, targetType string) string {
	if title == "" {
		title = "Draft wiki candidate"
	}
	if targetWiki == "" {
		targetWiki = "dev-fundamentals"
	}
	if targetType == "" {
		targetType = "notes"
	}
	return fmt.Sprintf(`---
title: %q
source: "agent-notes"
target_wiki: %q
target_type: %q
summary: "Draft generated by a host agent for human review."
suggester: "host-agent"
---`, title, targetWiki, targetType)
}

func StripMarkdownFence(output string) string {
	trimmed := strings.TrimSpace(output)
	if !strings.HasPrefix(trimmed, "```") {
		return trimmed
	}
	lines := strings.Split(trimmed, "\n")
	if len(lines) < 3 || strings.TrimSpace(lines[len(lines)-1]) != "```" {
		return trimmed
	}
	return strings.Join(lines[1:len(lines)-1], "\n")
}

func StripLLMOutputPreamble(output string) string {
	lines := strings.Split(strings.TrimSpace(output), "\n")
	for len(lines) > 0 {
		line := strings.TrimSpace(lines[0])
		if line == "" || strings.HasPrefix(line, "ULTRAWORK MODE ENABLED") {
			lines = lines[1:]
			continue
		}
		break
	}
	return strings.Join(lines, "\n")
}

var slugInvalid = regexp.MustCompile(`[^a-z0-9]+`)

func Slugify(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	value = slugInvalid.ReplaceAllString(value, "-")
	value = strings.Trim(value, "-")
	if value == "" {
		return "draft"
	}
	return value
}
