# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-harness" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b588fc2f507d0a7725f400e8d03c40d4a0c2c8d626edd028af52e987ba200602"
      url "https://github.com/m16khb/agent-harness/releases/download/v#{version}/agent-harness_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1edbe637400c8e924c5a52e7946aa403f851a8476a8cad078dda9b72fc9156af"
      url "https://github.com/m16khb/agent-harness/releases/download/v#{version}/agent-harness_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "63edbab6c488d71309691fa617db3c7705142fea9cd2f9d7393d1516f407f013"
      url "https://github.com/m16khb/agent-harness/releases/download/v#{version}/agent-harness_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e9440eada8f9466a1ebe29a7b112cfbfa8a6cc47e84ddd2bb7f7230e55a8f747"
      url "https://github.com/m16khb/agent-harness/releases/download/v#{version}/agent-harness_linux_arm64.tar.gz"
    end
  end

  name "agent-harness"
  desc "Shared Codex/Claude Code agent harness CLI, MCP, and hooks"
  homepage "https://github.com/m16khb/agent-harness"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-harness"

  # No zap stanza required

  caveats <<~EOS
    Wire the native Codex/Claude integrations (hooks, MCP, skills) with:
      agent-harness install-native
    The agent-harness daemon auto-starts when a host launches the MCP server.
  EOS
end
