package draftwiki

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

func writeSuggestedDraft(root, title, targetWiki, targetType, agyModel, output string) (string, error) {
	body := strings.TrimSpace(stripAgyOutputPreamble(stripMarkdownFence(output)))
	if body == "" {
		return "", fmt.Errorf("agy output was empty")
	}
	if !strings.HasPrefix(body, "---\n") {
		body = generatedDraftFrontmatter(title, targetWiki, targetType, agyModel) + "\n" + body + "\n"
	}
	meta := parseDraftWikiFrontmatter(body)
	draftTitle := meta["title"]
	if draftTitle == "" {
		draftTitle = title
	}
	if draftTitle == "" {
		draftTitle = "draft wiki candidate"
	}
	filename := time.Now().Format(time.DateOnly) + "-" + slugifyDraftWiki(draftTitle) + ".md"
	path := filepath.Join(root, filepath.FromSlash(DraftWikiDir), "draft", filename)
	if _, err := os.Stat(path); err == nil {
		return "", fmt.Errorf("draft already exists: %s", path)
	} else if !os.IsNotExist(err) {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(body+"\n"), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func generatedDraftFrontmatter(title, targetWiki, targetType, agyModel string) string {
	if title == "" {
		title = "Draft wiki candidate"
	}
	if targetWiki == "" {
		targetWiki = "dev-fundamentals"
	}
	if targetType == "" {
		targetType = "notes"
	}
	return fmt.Sprintf(`---
title: %q
source: "claude-mem"
target_wiki: %q
target_type: %q
summary: "Draft generated by agy for human review."
suggester: "agy -p"
model: %q
---`, title, targetWiki, targetType, agyModel)
}

func stripMarkdownFence(output string) string {
	trimmed := strings.TrimSpace(output)
	if !strings.HasPrefix(trimmed, "```") {
		return trimmed
	}
	lines := strings.Split(trimmed, "\n")
	if len(lines) < 3 || strings.TrimSpace(lines[len(lines)-1]) != "```" {
		return trimmed
	}
	return strings.Join(lines[1:len(lines)-1], "\n")
}

func stripAgyOutputPreamble(output string) string {
	lines := strings.Split(strings.TrimSpace(output), "\n")
	for len(lines) > 0 {
		line := strings.TrimSpace(lines[0])
		if line == "" || strings.HasPrefix(line, "ULTRAWORK MODE ENABLED") {
			lines = lines[1:]
			continue
		}
		break
	}
	return strings.Join(lines, "\n")
}

var draftWikiSlugInvalid = regexp.MustCompile(`[^a-z0-9]+`)

func slugifyDraftWiki(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	value = draftWikiSlugInvalid.ReplaceAllString(value, "-")
	value = strings.Trim(value, "-")
	if value == "" {
		return "draft"
	}
	return value
}
